#!/bin/bash
install() {
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git redis-server g++ libjansson-dev libpython-dev expat libexpat1-dev tmux subversion
cd ..
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz
 tar zxpf luarocks-2.2.2.tar.gz
 cd luarocks-2.2.2
 ./configure; sudo make bootstrap
 sudo luarocks install luasocket
 sudo luarocks install luasec
 sudo luarocks install redis-lua
 sudo luarocks install lua-term
 sudo luarocks install serpent
 sudo luarocks install dkjson
 sudo luarocks install lanes
 sudo luarocks install Lua-cURL
sudo luarocks install luaxmlrpc
cd ..
sudo apt-get install libstdc++9
sudo apt-get install libconfig++9v5 libstdc++6
sudo apt-get install libstdc++6
sudo apt-get install lua-lgi
sudo apt-get install libnotify-dev
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo chmod +x *
}
config() {
mkdir $HOME/.telegram-bot; cat <<EOF > $HOME/.telegram-bot/config
default_profile = "main";
main = {
lua_script = "$HOME/self/bot.lua";
};
EOF
printf "\n $f3 عملیات با موفقیت انجام شد\n"
}
launch() {
./tg | grep -v "{"
}
miladcli() {
./tg -p main --login --phone=${1}
} 
case $1 in
b)
config ${2}
exit ;;
c)
echo "شماره ربات را بدون فاصله وارد کنید"
read phone_number
miladcli ${phone_number}
exit;;
a)
install
exit;;
on)
echo "ربات با موفقیت فعال شد"
launch
exit;;
esac
exit 0